# Generated by Django 6.0.5 on 2026-06-01 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(db_column='idPersona', primary_key=True, serialize=False)),
                ('nombrePersona', models.CharField(db_column='nombrePersona', max_length=50)),
                ('apellidoPersona', models.CharField(blank=True, db_column='apellidoPersona', max_length=50, null=True)),
                ('sexoPersona', models.CharField(db_column='sexoPersona', default='Prefiero no Decirlo', max_length=20)),
                ('anioNacimientoPersona', models.DateField(db_column='anioNacimientoPersona')),
                ('correoPersona', models.EmailField(db_column='correoPersona', max_length=75, unique=True)),
                ('tipoPersona', models.CharField(db_column='tipoPersona', max_length=10)),
                ('contrasenaPersona', models.CharField(db_column='contrasenaPersona', max_length=255)),
                ('fotoPerfilPersona', models.BinaryField(blank=True, db_column='fotoPerfilPersona', max_length='max', null=True)),
            ],
            options={
                'db_table': '"Identidad"."Persona"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('persona', models.OneToOneField(db_column='idPersona', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='perfil_usuario', serialize=False, to='core.persona')),
                ('usernameUsuario', models.CharField(db_column='usernameUsuario', max_length=75, unique=True)),
                ('ciudadUsuario', models.CharField(db_column='ciudadUsuario', max_length=50)),
                ('metodoPago', models.CharField(blank=True, db_column='metodoPago', max_length=25, null=True)),
                ('estadoSuscripcion', models.CharField(blank=True, db_column='estadoSuscripcion', max_length=10, null=True)),
                ('paisOrigenUsuario', models.IntegerField(db_column='paisOrigenUsuario')),
                ('paisResidenciaUsuario', models.IntegerField(db_column='paisResidenciaUsuario')),
                ('Suscripcion_idSuscripcion', models.IntegerField(blank=True, db_column='Suscripcion_idSuscripcion', null=True)),
                ('Genero_idGenero', models.IntegerField(blank=True, db_column='Genero_idGenero', null=True)),
                ('Emocion_idEmocion', models.IntegerField(blank=True, db_column='Emocion_idEmocion', null=True)),
            ],
            options={
                'db_table': '"Identidad"."Usuario"',
                'managed': False,
            },
        ),
    ]
