# Generated by Django 6.0.5 on 2026-06-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='[Identidad].[Persona]',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='[Identidad].[Usuario]',
        ),
    ]
